name: Proto Build and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout proto Repository
        uses: actions/checkout@v4
        with:
          path: proto

      - name: Checkout proto-gen Repository
        uses: actions/checkout@v4
        with:
          repository: kzelealem/proto-gen
          path: proto-gen

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Latest Go
        uses: actions/setup-go@v5
        with:
          go-version: 'latest'  # Automatically uses the latest stable Go version

      - name: Install Go Protobuf Plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install Go Protobuf Plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

      - name: Update Go Dependencies
        run: |
          cd /home/runner/work/proto/proto/proto-gen
          go get -u ./...
          go mod tidy

      - name: Run Build Scripts
        run: |
          chmod +x /home/runner/work/proto/proto/proto/go-build.sh /home/runner/work/proto/proto/proto/swagger-build.sh
          /home/runner/work/proto/proto/proto/go-build.sh /home/runner/work/proto/proto/proto /home/runner/work/proto/proto/proto-gen/go
          /home/runner/work/proto/proto/proto/swagger-build.sh /home/runner/work/proto/proto/proto /home/runner/work/proto/proto/proto-gen/swagger

      - name: Commit, Tag, and Push Changes in proto-gen
        run: |
          cd /home/runner/work/proto/proto/proto-gen
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add -A
          git commit -m "Auto-generated code for ${GITHUB_REF/refs\/tags\/v/}"
          git tag -a "${GITHUB_REF/refs\/tags\/}" -m "Auto-generated tag ${GITHUB_REF/refs\/tags\/}"
          git push origin main
          git push origin "${GITHUB_REF/refs\/tags\/}"
